// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxqyuGPl2GDHJzf2OXOsRJJVfn-Irlshs',
    appId: '1:283247980694:web:425e15efb97867cde952b7',
    messagingSenderId: '283247980694',
    projectId: 'sura-dev-2292d',
    authDomain: 'sura-dev-2292d.firebaseapp.com',
    storageBucket: 'sura-dev-2292d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzoTgoEWK8citS4fw_ga1y5sPZSqNFSF8',
    appId: '1:283247980694:android:d16b773f5046b23ee952b7',
    messagingSenderId: '283247980694',
    projectId: 'sura-dev-2292d',
    storageBucket: 'sura-dev-2292d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPd11t67jDbKGZwGDZmafhnyfxxH_-rvA',
    appId: '1:283247980694:ios:58875429c8ede768e952b7',
    messagingSenderId: '283247980694',
    projectId: 'sura-dev-2292d',
    storageBucket: 'sura-dev-2292d.firebasestorage.app',
    iosBundleId: 'com.sura.suraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPd11t67jDbKGZwGDZmafhnyfxxH_-rvA',
    appId: '1:283247980694:ios:58875429c8ede768e952b7',
    messagingSenderId: '283247980694',
    projectId: 'sura-dev-2292d',
    storageBucket: 'sura-dev-2292d.firebasestorage.app',
    iosBundleId: 'com.sura.suraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxqyuGPl2GDHJzf2OXOsRJJVfn-Irlshs',
    appId: '1:283247980694:web:a4a6b9d73c362596e952b7',
    messagingSenderId: '283247980694',
    projectId: 'sura-dev-2292d',
    authDomain: 'sura-dev-2292d.firebaseapp.com',
    storageBucket: 'sura-dev-2292d.firebasestorage.app',
  );
}
