// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVcq_ZoZBCBSBOoFAwtwGZ3Q7U9uMpkWU',
    appId: '1:636441610129:web:312a524c42f615e7967c30',
    messagingSenderId: '636441610129',
    projectId: 'sura-eb4db',
    authDomain: 'sura-eb4db.firebaseapp.com',
    storageBucket: 'sura-eb4db.firebasestorage.app',
    measurementId: 'G-518915KCQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwM3NU_Bjj1l2DxcmXiO2eVEZJbbg4Pe8',
    appId: '1:636441610129:android:c8a4ef6d9791851c967c30',
    messagingSenderId: '636441610129',
    projectId: 'sura-eb4db',
    storageBucket: 'sura-eb4db.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6prN-nk1Aknxn9oDwGG9iR-_0MSYny4E',
    appId: '1:636441610129:ios:16354e5296c5d72c967c30',
    messagingSenderId: '636441610129',
    projectId: 'sura-eb4db',
    storageBucket: 'sura-eb4db.firebasestorage.app',
    iosClientId: '636441610129-tsrp90moeshjcuaae8nocoj5kh03e06i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sura',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6prN-nk1Aknxn9oDwGG9iR-_0MSYny4E',
    appId: '1:636441610129:ios:16354e5296c5d72c967c30',
    messagingSenderId: '636441610129',
    projectId: 'sura-eb4db',
    storageBucket: 'sura-eb4db.firebasestorage.app',
    iosClientId: '636441610129-tsrp90moeshjcuaae8nocoj5kh03e06i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVcq_ZoZBCBSBOoFAwtwGZ3Q7U9uMpkWU',
    appId: '1:636441610129:web:85e583f75967d28d967c30',
    messagingSenderId: '636441610129',
    projectId: 'sura-eb4db',
    authDomain: 'sura-eb4db.firebaseapp.com',
    storageBucket: 'sura-eb4db.firebasestorage.app',
    measurementId: 'G-GWP31KR89R',
  );
}
